language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
env:
  global:
    - secure: "p5n63PrJdyN7S9G4rWGAn2RpMP78mWkIIaNLCIX2S9Sqngae/NiGUo2Ik/PPG20VKjRz+5CE/88VPDXmag2c8gnJvBLXF1QNy4Sj/R8N6/wvcn7VMEt6AjNkjKHESwXjL8Hqh1dYAyvzVHRZwgXClkKQB2o+60zFns8hcIrbizY="
    - secure: "ao3VUe2VaUPrrZr4rbGNUqWnNLT0WRI1S3AVRXfEn5fRtf0QsBuJYMmqichFAKkMsXI3sI0mQt5aQ9pwKd1XpswNxiIr9TWAT76x08Yrb+JsosIrZj+kG2qIfc6Zb/NSu2gRgUPYFSHI0Z+LoT6mLuFi6kNC58JU6LoabQMn8L4="
    - secure: "JIjo9LnG8eamZ0qLNRmVoyjwA2r1NN74oFGxPiITkcp5otd96Pr7wjNTpc05br9wEQwc7MOot6cBO1I+Sp5A4yl3Btg72NfWebz0/8XQXgFfRMH5yI6miKVreHt2o1j+71jHkDntWg1JFn9PWmsWo7ZT562ISOkYdtMANH5/HhI="
    - secure: "lQZz8BKOlDEtgkG8X/UaTfIA2FLziG1cJcPR0/vm5Bm7djjCLgsX+H6RIJ4DYlV8x962fEKYw6TDOqtdKUhluQRr4lQn5tVwzYUjJKzcOU01pvGHebJIG6EWckLxWzIPfbZ/gb7fIblKXOfj7dYfJ9lSBRkRK7QvZdFSl/K5kjQ="
    - secure: "sxR5IIiD1Vnb9pG9BypKF91MwQAp9JuFJ/3x7vLxXHMB/IquoANSfIkEMB/qSWlBHkbQjDgbZpILnH/3EUfZLORdeNjV1OMjdX5ItLJrEF3cvo/V6hl6+t13plu+IJK5dfJ/75vfx65AT90Fyph0gC7Z79X1HIJqwSG9vfQglDI="

script:
  - bundle exec rake db:migrate RACK_ENV=test
  - bundle exec rake spec